---
- name: Deploy matic mainnet full node
  hosts:
    - matic
  become: true
  vars:
    work_dir: /data/git
    build_dir: /data/build
    heimdall_version: v0.2.1-mainnet
    heimdall_data_dir: "/data/vol/heimdall"
    heimdall_genesis_file: https://raw.githubusercontent.com/maticnetwork/launch/master/mainnet-v1/without-sentry/heimdall/config/genesis.json
    heimdall_seeds: "f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656"
    heimdall_amqp_url: "amqp://guest:guest@rabbitmq:5672"
  tasks:
    - include: pre.yml
      tags:
        - pre
    - include: docker-install.yml
      tags:
        - docker
    - include: heimdall.yml
      tags:
        - heimdall
